name: card_carousel
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/van_on_beach.jpg
     - assets/dusk_waves.jpg
     - assets/board_walk.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
     - family: petita
       fonts:
         - asset: assets/PetitaMedium.ttf
         - asset: assets/PetitaBold.ttf
           weight: 700
         - asset: assets/PetitaLight.ttf
           weight: 300
     - family: gidole
       fonts:
         - asset: assets/Gidole-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
